name: PSScriptAnalyzer

on:
  push:
    branches: [ master ]
    paths:
      - '**.ps1'
  pull_request:
    branches: [ master ]
    paths:
      - '**.ps1'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          recurse: true

      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: psscriptanalyzer
